package dev.kordx.commands.argument.extension

import dev.kordx.commands.argument.*
import dev.kordx.commands.argument.result.*
import dev.kordx.commands.argument.result.extension.orDefault
import dev.kordx.commands.argument.result.extension.orElse
import dev.kordx.commands.argument.result.extension.orElseSupply

/**
 * Returns an Argument that maps all [ArgumentResult.Failure] to a [ArgumentResult.Success]
 * with the given [default] value.
 */
fun <T : Any, CONTEXT> dev.kordx.commands.argument.Argument<T, CONTEXT>.withDefault(
        default: T
): dev.kordx.commands.argument.Argument<T, CONTEXT> = object : dev.kordx.commands.argument.Argument<T, CONTEXT> by this {
    override suspend fun parse(text: String, fromIndex: Int, context: CONTEXT): ArgumentResult<T> {
        return this@withDefault.parse(text, fromIndex, context).orElse(fromIndex, default)
    }
}

/**
 * Returns an Argument that maps all [ArgumentResult.Failure] to a [ArgumentResult.Success]
 * with a value generated by [default].
 */
fun <T : Any, CONTEXT> dev.kordx.commands.argument.Argument<T, CONTEXT>.withDefault(
        default: suspend CONTEXT.() -> T
): dev.kordx.commands.argument.Argument<T, CONTEXT> = object : dev.kordx.commands.argument.Argument<T, CONTEXT> by this {

    override suspend fun parse(text: String, fromIndex: Int, context: CONTEXT): ArgumentResult<T> {
        return this@withDefault.parse(text, fromIndex, context).orElseSupply(fromIndex) { default(context) }
    }
}

/**
 * Returns an Argument that maps all [ArgumentResult.Success] with a `null` value and [ArgumentResult.Failure]
 * to a [ArgumentResult.Success] with the given [default] value.
 */
@Suppress("UNCHECKED_CAST")
@JvmName("withDefaultNullable")
fun <T : Any, CONTEXT> dev.kordx.commands.argument.Argument<T?, CONTEXT>.withDefault(
        default: T
): dev.kordx.commands.argument.Argument<T, CONTEXT> = object : dev.kordx.commands.argument.Argument<T, CONTEXT> by this as dev.kordx.commands.argument.Argument<T, CONTEXT> {

    override suspend fun parse(text: String, fromIndex: Int, context: CONTEXT): ArgumentResult<T> {
        return this@withDefault.parse(text, fromIndex, context).orDefault(default)
    }
}

/**
 * Returns an Argument that maps all [ArgumentResult.Success] with a `null` value and [ArgumentResult.Failure]
 * to a [ArgumentResult.Success] with a value generated by [fallback].
 */
@Suppress("UNCHECKED_CAST")
@JvmName("withDefaultNullable")
fun <T : Any, CONTEXT> dev.kordx.commands.argument.Argument<T?, CONTEXT>.withDefault(
        fallback: suspend CONTEXT.() -> T
): dev.kordx.commands.argument.Argument<T, CONTEXT> = object : dev.kordx.commands.argument.Argument<T, CONTEXT> by this as dev.kordx.commands.argument.Argument<T, CONTEXT> {

    override suspend fun parse(text: String, fromIndex: Int, context: CONTEXT): ArgumentResult<T> {
        return this@withDefault.parse(text, fromIndex, context).orElseSupply(fromIndex) { fallback(context) }
    }
}
