package dev.kord.x.commands.argument.extension

import dev.kord.x.commands.argument.Argument
import dev.kord.x.commands.argument.result.ArgumentResult
import dev.kord.x.commands.argument.result.extension.FilterResult
import dev.kord.x.commands.argument.result.extension.filter

/**
 * Returns a new Argument that limits the acceptable range of values to the [range].
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
fun <T, CONTEXT> Argument<T, CONTEXT>.inRange(
    range: ClosedRange<T>
): Argument<T, CONTEXT> where T : Number, T : Comparable<T> =
    object : Argument<T, CONTEXT> by this {

        override suspend fun parse(
            text: String,
            fromIndex: Int,
            context: CONTEXT
        ): ArgumentResult<T> {
            return this@inRange.parse(text, fromIndex, context).filter(fromIndex) {
                if (it in range) FilterResult.Pass
                else FilterResult.Fail("expected number in range of [${range.start}..${range.endInclusive}]")
            }
        }

    }

/**
 * Returns a new Argument that limits the acceptable range of values to positive numbers (including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("longPositive")
fun <CONTEXT> Argument<Long, CONTEXT>.positive(): Argument<Long, CONTEXT> =
    inRange(0L..Long.MAX_VALUE)

/**
 * Returns a new Argument that limits the acceptable range of values to positive numbers (not including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("longStrictPositive")
fun <CONTEXT> Argument<Long, CONTEXT>.strictPositive(): Argument<Long, CONTEXT> =
    inRange(1L..Long.MAX_VALUE)

/**
 * Returns a new Argument that limits the acceptable range of values to negative numbers (including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("longNegative")
fun <CONTEXT> Argument<Long, CONTEXT>.negative(): Argument<Long, CONTEXT> = filter {
    if (it <= 0) FilterResult.Pass
    else FilterResult.Fail("expected number in range of [${Long.MIN_VALUE}..0]")
}

/**
 * Returns a new Argument that limits the acceptable range of values to negative numbers (not including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("longStrictNegative")
fun <CONTEXT> Argument<Long, CONTEXT>.strictNegative(): Argument<Long, CONTEXT> = filter {
    if (it <= -1) FilterResult.Pass
    else FilterResult.Fail("expected number in range of [${Long.MIN_VALUE}..-1]")
}

/**
 * Returns a new Argument that limits the acceptable range of values to positive numbers (including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("intPositive")
fun <CONTEXT> Argument<Int, CONTEXT>.positive(): Argument<Int, CONTEXT> =
    inRange(0..Int.MAX_VALUE)

/**
 * Returns a new Argument that limits the acceptable range of values to positive numbers (not including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("intStrictPositive")
fun <CONTEXT> Argument<Int, CONTEXT>.strictPositive(): Argument<Int, CONTEXT> =
    inRange(1..Int.MAX_VALUE)

/**
 * Returns a new Argument that limits the acceptable range of values to negative numbers (including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("intNegative")
fun <CONTEXT> Argument<Int, CONTEXT>.negative(): Argument<Int, CONTEXT> =
    filter {
        if (it <= 0) FilterResult.Pass
        else FilterResult.Fail("expected number in range of [${Int.MIN_VALUE}..0]")
    }

/**
 * Returns a new Argument that limits the acceptable range of values to negative numbers (not including 0).
 *
 * > Examples generated by this argument will only consider the current range. More complex Arguments
 * might thus return invalid example values.
 */
@JvmName("LongStrictNegative")
fun <CONTEXT> Argument<Int, CONTEXT>.strictNegative(): Argument<Int, CONTEXT> =
    filter {
        if (it <= -1) FilterResult.Pass
        else FilterResult.Fail("expected number in range of [${Int.MIN_VALUE}..-1]")
    }
